### ISSUE TITLE
Is it possible to get the BASE stats that make up a COMPOSITE stat via H2H matchups?

### ISSUE THREAD

**Issue by chrisk1250** [edwarddistel/yahoo-fantasy-baseball-reader#10]
Do you know if it's possible to also obtain the data that goes into the composite stats when using the Scoreboard API for Fantasy Baseball H2H matchups? For example, within this API call, I would absolutely love to get all the stuff that makes up OPS. I know Yahoo has it all behind the scenes! Does anyone know of a way to do this at all?

Are you only able to obtain the stat categories that are defined on your league? Or is there some documented/undocumented route or query parameter to also request specific stat categories as well (in addition to what you specify as your H2H categories in your league)?

**Comment by edwarddistel** [comment]
Not that I know of.

Let's say you want to know how the OPS was calculated in a H2H matchup. It would be the sum of every _starting_ players' OPS for each day of the week.

Pulling a player's game stats is easy enough but how to cross-reference that with who started which day?

I've looked through the Yahoo documentation and didn't see anything like what I think you're asking for, but if you find something let me know!
