### ISSUE TITLE
Can you add/drop players on the Transaction Subresource?

### ISSUE THREAD

**Issue by tomtam6** [edwarddistel/yahoo-fantasy-baseball-reader#11]
I'm trying understand if a PUT can be used to add/drop players from free agency.

**Comment by edwarddistel** [comment]
You can, but using POST and not PUT.

Details here: https://web.archive.org/web/20130824063733/http://developer.yahoo.com/fantasysports/guide/transactions-collection.html (God bless the Internet Archive and the Wayback Machine!)

URL to post to: 
http://fantasysports.yahooapis.com/fantasy/v2/league/{league_key}/transactions

Sample payload:

```xml
<fantasy_content>  
  <transaction>  
    <type>add</type>  
    <player>  
      <player_key>{player_key}</player_key>  
      <transaction_data>  
        <type>add</type>  
        <destination_team_key>{team_key}</destination_team_key>  
      </transaction_data>  
    </player>  
  </transaction>  
</fantasy_content>  
```

Good luck!
