### ISSUE TITLE
Yahoo football?

### ISSUE THREAD

**Issue by tomtam6** [edwarddistel/yahoo-fantasy-baseball-reader#13]
Are you interested in creating something for fantasy football? I'm having a tough time following documentation.

**Comment by edwarddistel** [comment]
Hi @tomtam6 ,

What I have should work for football, too! Is it not working for you?

What error messages are you getting?

**Comment by tomtam6** [comment]
Upon the initial npm install command, error returned:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xx.xxx\AppData\Roaming\npm-cache\_logs\2021-06-18T22_34_24_577Z-debug.log


*Note
xx.xxx = obfuscated file path

**Comment by edwarddistel** [comment]
If it's an error with installing the NodeJS dependencies it's most likely a problem with the version of NodeJS you are running and not the application itself.

What version of Node are you running?

Try `nvm use` to ensure you're using the Node version specified in the `.nvmrc` file. If you don't have that version installed it should prompt you with instructions on how to install that version of Node.

If you have the right version of Node running and it still doesn't work, let me know.

**Comment by tomtam6** [comment]
npm: '6.13.4'
The .nvmrc file states: v15.4.0?

Sorry node is somewhat new territory for me.

**Comment by edwarddistel** [comment]
`npm` is a package manager for node and actually distinct from the node binary. You would type `node --version` to see what version you're on.

https://tecadmin.net/lock-application-with-specific-node-version/ has some details on how to use the `.nvmrc` file.
