### ISSUE TITLE
Step 14: League Key

### ISSUE THREAD

**Issue by tomtam6** [edwarddistel/yahoo-fantasy-baseball-reader#14]
Hi there - I need assistance obtaining this value. I am attempting this app for Fantasy Football. I'm stuck at obtaining the prefix.

When I run npm run league-prefix I receive a 404 response.

**Comment by edwarddistel** [comment]
Hi @tomtam6 -- that's not an error, the league prefix number for 2021 is actually 404. Unfortunate coincidence that it shares the number for the HTTP error code of page not found, but you are getting the correct value.

**Comment by tomtam6** [comment]
Wow, thank you.
