### ISSUE TITLE
Error with credentials

### ISSUE THREAD

**Issue by LeoFonsecaP** [edwarddistel/yahoo-fantasy-baseball-reader#16]
Hi,
First thing I want to do is congratulate the great work you did with all this code.
I also wanted to ask you if there´s a likely cause for "Error with credentials in makeAPIrequest()/refreshAuthorizationToken(): Error: Request failed with status code 403". Not sure if I forgot something, the fantasy API is super confusing.
Thank you!

**Comment by edwarddistel** [comment]
Hi @LeoFonsecaP ,

Does the first call work? That is, when you first invoke it, do you get results? The error message you're copying and pasting is about the refresh token.

If it's only refreshing the token that's the problem, that you're able to get your initial data back, then possible you might have a permissions problem -- the app needs to write to the directory you specify in the config file to save refresh tokens. If it can't save there it won't be able to successfully refresh.

If you don't get the initial results then something is wrong in your config -- I'd recommend stepping through the installation and configuration steps carefully, it can be confusing.

Good luck!

**Comment by LeoFonsecaP** [comment]
Hey, the problem was that I used the code from last year's league, so the API tried pulling data from the correspondent this year and I was getting an authorization error (403), due to not being in the league.

**Comment by edwarddistel** [comment]
Glad you figured out the issue. Good luck.
