### ISSUE TITLE
Limited to first 25 Free Agents

### ISSUE THREAD

**Issue by orangesuave** [edwarddistel/yahoo-fantasy-baseball-reader#9]
Hello @edwarddistel! First of all congratulations on your achievement. These tools you've built are tremendous. This is technically not an issue since I'm sure it's functioning the way you intended; however, a suggestion would be to update this method so that it iterates over n number of players (to be specified by the user in config.json during setup). Currently we only ever see the top 25 free agent candidates (sorted by overall rank). This makes it nearly impossible to find players returning from injury, new call-ups, or even just those players who are currently underperforming and are potentially solid buy-low candidates. 

https://github.com/edwarddistel/yahoo-fantasy-baseball-reader/blob/c17effdc65aee388f837b4affe26d99fe9894172/src/yahooFantasyBaseball.js#L23:L24

**Comment by edwarddistel** [comment]
Hi @orangesuave,

Sorry for the delay in my response, this is just a fun side project for me.

You're right, so I added the ability to return as many free agents as you want.

There's a new field in the `config.json` file, `FREE_AGENTS`. By default I set it to 3 (first 100) but you can request as many as you want just by changing the config.

Let me know if you run into any problems.

**Comment by orangesuave** [comment]
No need to apologize. I appreciate that you took the time to consider a
good approach and  respond. I look forward to trying these out when I get
some free time of my own. ;-)
